name: Publish GitHub Release (Fork)

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  build-for-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install core dependencies
        run: npm install --omit=dev

      - name: Install GUI dependencies
        working-directory: ./gui
        run: |
          npm install file:.. --save
          npm install

      - name: Fix GUI Naming
        working-directory: ./gui
        run: |
          sed -i '' 's/@g3ntl3ma\/green-tunnel-gui/green-tunnel/g' package.json
          sed -i '' 's/@g3ntl3ma\/green-tunnel-gui/green-tunnel/g' package-lock.json

      - name: Generate icons
        working-directory: ./gui
        run: npm run generate-icons

      - name: Build for macOS
        working-directory: ./gui
        run: npm run package-mac

      - name: Zip
        working-directory: ./gui/release-builds/green-tunnel-darwin-x64
        run: zip -r green-tunnel-macos.zip green-tunnel.app

      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: builds-mac
          path: ./gui/release-builds/green-tunnel-darwin-x64/green-tunnel-macos.zip

  build-for-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install core dependencies
        run: npm install --omit=dev

      - name: Install GUI dependencies
        working-directory: ./gui
        run: |
          npm install file:.. --save
          npm install

      - name: Fix GUI Naming
        working-directory: ./gui
        run: |
          powershell -Command "(gc package.json) -replace '@g3ntl3ma/green-tunnel-gui', 'green-tunnel' | Out-File -encoding ASCII package.json"
          powershell -Command "(gc package-lock.json) -replace '@g3ntl3ma/green-tunnel-gui', 'green-tunnel' | Out-File -encoding ASCII package-lock.json"

      - name: Generate icons
        working-directory: ./gui
        run: npm run generate-icons

      - name: Build for Windows
        working-directory: ./gui
        run: npm run package-win

      - name: Add Windows Installer
        working-directory: ./gui
        run: npm run windows-installer

      - name: Zip
        working-directory: ./gui/release-builds/green-tunnel/windows-installer
        run: Compress-Archive -Path green-tunnel-installer.exe -DestinationPath green-tunnel-windows.zip

      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: builds-windows
          path: ./gui/release-builds/green-tunnel/windows-installer/green-tunnel-windows.zip

  build-for-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install core dependencies
        run: npm install --omit=dev

      - name: Install GUI dependencies
        working-directory: ./gui
        run: |
          npm install file:.. --save
          npm install
          npm install -g electron-installer-debian

      - name: Fix GUI Naming
        working-directory: ./gui
        run: |
          sed -i 's/@g3ntl3ma\/green-tunnel-gui/green-tunnel/g' package.json
          sed -i 's/@g3ntl3ma\/green-tunnel-gui/green-tunnel/g' package-lock.json

      - name: Generate icons
        working-directory: ./gui
        run: npm run generate-icons

      - name: Build for Linux
        working-directory: ./gui
        run: npm run package-linux

      - name: Add Linux Installer
        working-directory: ./gui
        run: npm run linux-installer

      - name: Zip
        working-directory: ./gui/release-builds
        run: zip -r green-tunnel-debian.zip *.deb

      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: builds-linux
          path: ./gui/release-builds/green-tunnel-debian.zip

  new-release:
    runs-on: ubuntu-latest
    needs: [build-for-mac, build-for-windows, build-for-linux]
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: builds-*
          merge-multiple: true
          path: builds/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            builds/green-tunnel-macos.zip
            builds/green-tunnel-windows.zip
            builds/green-tunnel-debian.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
